-- Add extractive-extraction metadata to document_metadata table
-- This migration adds columns for rich date entities and summary provenance
-- produced by the deterministic date extraction and extractive ranking stages.

-- Rich date entities extracted by the deterministic date NER stage
ALTER TABLE document_metadata
ADD COLUMN IF NOT EXISTS dates_json JSONB;

-- Key points produced by the LLM summary-polishing stage
ALTER TABLE document_metadata
ADD COLUMN IF NOT EXISTS summary_key_points JSONB;

-- Source sentences (with page numbers) used to build the summary
ALTER TABLE document_metadata
ADD COLUMN IF NOT EXISTS summary_source_sentences JSONB;

-- Which pipeline produced this metadata: extractive_small | extractive_large | legacy_llm
ALTER TABLE document_metadata
ADD COLUMN IF NOT EXISTS pipeline_method VARCHAR(30);

-- Add comments for documentation
COMMENT ON COLUMN document_metadata.dates_json IS 'Rich date entities extracted deterministically (raw, normalized dd/mm/yyyy, page, sentence, context, event_type/event_label)';
COMMENT ON COLUMN document_metadata.summary_key_points IS 'Key points generated by the LLM polishing stage';
COMMENT ON COLUMN document_metadata.summary_source_sentences IS 'Page-annotated source sentences used for the extractive summary';
COMMENT ON COLUMN document_metadata.pipeline_method IS 'Metadata pipeline that produced this row';